### ISSUE TITLE
Add `RasterPathBandTupleError` exception

### ISSUE THREAD

**Issue by richpsharp** [natcap/pygeoprocessing#104]
In general a malformed raster path/band tuple in PyGeoprocessing gets a `ValueError` raised. This is mostly for programmer convenience because it's essentially a syntax error but we don't have static type checking in Python. It'd look nicer to have a `RasterpathBandTupleError` exception to make it so the programmer need not just read the error message. We might also build in the error message directly into the class ensure consistent error messaging there.

It's possible there are other custom exceptions that might be helpful in PyGeoprocessing so look for them when processing this issue. If possible, it's nice to keep custom exceptions internal and provide built-in python exceptions to the public facing side of the API. And if there are cases where custom exceptions would be helpful in differentiating between reasonable exception behavior, it'll be worth considering the orthogonality of functions that do so.

**Comment by richpsharp** [comment]
I can't remember why I added this -- I can't think of an actual use case where I've been confused by it or heard someone who has. No need to write code just for that!

**Comment by dcdenu4** [comment]
Hey @richpsharp I think this came up when we were talking about adding the `ReclassificationMissingValuesError` exception. I think I was mentioning that `reclassify_raster` could raise `ValueError` multiple times, and we had talked about how that was okay, but maybe the `ValueError` on handling bad raster path / band tuples should be a PGP Exception class since it's widely used throughout the module. 

Anyway, that's how I remember it and wanted to provide context here. No need to reopen.

**Comment by richpsharp** [comment]
Hi @dcdenu4, I didn't mean to close an issue on you! Of course I remember the `ReclassificationMissingValuesError` -- we just did it! But I'm sorry I don't remember discussing this one. The `ReclassificationMissingValuesError` is compelling because there is reasonable behavior you can do at runtime if you understand the error and a calculation you can do that would be order-of-magnitude inefficient to do outside of the context of the exception. 

In the case of this proposed issue, I haven't encountered a raster path/band tuple error outside the context of development. I also don't recall being confused by the error message it raises when I do encounter it during development... That's why I was surprised I made the issue at all. In fact I was wondering if I was confused once, got annoyed, and then made this issue?

Can you provide more context to this? Anything similar to `ReclassificationMissingValuesError` where having a custom exception will save on computation or regular old confusion or something else?

**Comment by dcdenu4** [comment]
Oy, I think that's all the context I can remember! I think you're right and that there is nothing compelling about making a custom exception for this. I don't think there is any computational upside scenario and I don't think it's very confusing to get a `ValueError` for this. I do think that a custom exception would be bloatware. I'll close this down!
