### ISSUE TITLE
Proposal: allow missing values to be accessed as attributes of a reclassification exception

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#105]
In InVEST, we are looking to create more readable error messages when a table-based reclassification fails, and the way that we think these messages will be most useful will be if we can provide more contextual information about the error. The error that is raised by `pygeoprocessing.reclassify_raster`, while sensible for us as programmers who already understand the context of the exception, does not allow for the useful information to be accessed without some string parsing.

I propose that a custom exception be raised when values are missing from the `value_map`.  The purpose of this exception is to:

1. Allow the exception relating to missing values to be caught and have that error handled apart from other errors that might be raised by `reclassify_raster`
2. Allow the relevant attributes of the reclassification to be accessed as attributes of the new exception such that they can be used in a higher-level exception that provides additional context that is specific to the InVEST model.  At present this is possible, but would require that we extract this information from the string text of the `ValueError` currently raised.  The relevant attributes here would be:
    * The set of `missing_values`
    * The `value_map`  (though I'm less worried about this, because this structure is still accessible at the point where InVEST calls `reclassify_raster`).
3. Continue to be a useful exception when called directly within a script by a developer, with a useful error message.

Example of how this could be used in InVEST:

```python
try:
    pygeoprocessing.reclassify_raster(...)
except pygeoprocessing.ReclassificationError as error:
    error_message = f'The biophysical table is missing rows with LULC code {error.missing_values}'
    raise ValueError(error_message)
```
    
Including @dcdenu4 since we had talked about this in the context of reclassifications across InVEST.

Also, this is related to #103.

What do you think about this @richpsharp ?

**Comment by dcdenu4** [comment]
Rich commented that this sounds good and that he'd recommend `ReclassificationMissingValuesError`
