### ISSUE TITLE
Determine outlets of raster

### ISSUE THREAD

**Issue by richpsharp** [natcap/pygeoprocessing#148]
It's often useful to see where the "outlets" are in a DEM. These are defined as internal sinks, drains to nodata, or drains to the edge of a raster. This test requires per-pixel testing and is only efficient without Pythonic loop overhead. Make a function that takes a D8 raster and creates a point vector output showing the outlets with additional annotations of the i/j coordinates in the dem.

**Comment by emlys** [comment]
this sounds almost identical to the delineateit 'detect pour points' feature that came out of https://github.com/natcap/invest/issues/147. Maybe that code should move over to pygeoprocessing

**Comment by richpsharp** [comment]
Ahh dang @emlys, I just wrote that this evening. Could I put you as the PR reviewer and you can decide what makes sense?

**Comment by richpsharp** [comment]
Oh actually that is not the same... A "pour point" is different than an outlet. I think what I'm making here is much simpler, it's just where the DEM would drain to nodata or an edge.

**Comment by richpsharp** [comment]
Okay @emlys, I'm gonna wait for James to approve the doozy of https://github.com/natcap/pygeoprocessing/pull/140 and then I'll do the PR for https://github.com/richpsharp/pygeoprocessing/tree/feature/outlet-maker-148 and request a review from you. Sorry to do it like this but it's a feature i need tonight for work that was due last week. :\

**Comment by emlys** [comment]
Ok sounds good! Is an "internal sink" where it drains to a nodata pixel that's in the middle of the raster? for the delineateit feature our definition of a "pour point" was: _the center point of a pixel which (1) flows off of the raster, or (2) flows into a nodata pixel._

**Comment by richpsharp** [comment]
Okay all yours @emlys: https://github.com/natcap/pygeoprocessing/pull/151



> Ok sounds good! Is an "internal sink" where it drains to a nodata pixel that's in the middle of the raster? for the delineateit feature our definition of a "pour point" was: _the center point of a pixel which (1) flows off of the raster, or (2) flows into a nodata pixel._

Yes, "internal sink" is just a shorthand for "nodata value in the middle of the raster but not on the edge. It's not otherwise a special case there.
