### ISSUE TITLE
Add raster stitching functionality

### ISSUE THREAD

**Issue by richpsharp** [natcap/pygeoprocessing#150]
A common use case is for a GIS pipeline to make many small rasters in different projections (say watersheds or countries) and then need a final result in a single raster. Non-trivial things:

* how should one handle different projections between base and target raster?
    * area invariant values should only need a pixel size change and a common interpolation rule
    * area variant values are difficult to handle in general, but perhaps lat/lng is an okay one to base everything off of?
* how should one handle base rasters which intersect with non-nodata values?
    * options to replace old, ignore new, or add
* how to handle batch processing of multi images

**Comment by phargogh** [comment]
Would a VRT work for this?

The few times I've needed to do this sort of thing, a VRT has been surprisingly slick.  One particular case I remember was where I was trying to use pygeoprocessing's merge_rasters function, and that didn't handle different nodata values ... But I out all those rasters into a VRT and it worked exactly like I hoped.

Not saying it'll be a silver bullet, but I think VRTs might get pretty darn close.

**Comment by richpsharp** [comment]
Yes VRTs do a lot of this stuff but I think maybe I buried the lead there: the tricky case is the one where the base raster has an area variant value that needs to be handled correctly when reprojecting to a different pixel size... think population count per pixel or water volume per pixel.  

The other nice to have feature is the one of continuous integration, such as results streaming from a multiprocessing solution that can be stitched in and deleted. The VRT of course would require a wait until the end, then stitch everything together... so an additional delay and disk space load. Maybe that doesn't sound like a big deal but it can be when you're doing hundreds of thousands of watershed rasters. That's the "how to handle batch processing of multi images".

Sorry I guess as a design doc this issue is not that

**Comment by richpsharp** [comment]
Boy now that you mention it, maybe this should replace `merge_rasters`. I'll take a look while I'm working on it.

**Comment by richpsharp** [comment]
Yeah looking more closely I sort of remember writing `merge_rasters` a long time ago... like i can remember brad was around, but it doesn't look that useful, especially considering all the rasters need to be in the same projection/pixel size.

**Comment by phargogh** [comment]
Yeah, when I tried it out, it _really_ wasn't that useful.  In addition to the pixel size constraints, the function tries (and failed in this case) to handle nodata values appropriately ... instead it would just copy new nodata values over existing pixel values where the VRT handled these differences perfectly.  It did feel like a relic from an earlier age.

> the tricky case is the one where the base raster has an area variant value that needs to be handled correctly when reprojecting to a different pixel size... think population count per pixel or water volume per pixel.

This sounds like a [VRT Derived Band](https://gdal.org/drivers/raster/vrt.html#using-derived-bands-with-pixel-functions-in-c-c).  I've never tried it myself, but neat to see that you could write a custom function to do this.

> The other nice to have feature is the one of continuous integration, such as results streaming from a multiprocessing solution that can be stitched in and deleted. The VRT of course would require a wait until the end, then stitch everything together... so an additional delay and disk space load. Maybe that doesn't sound like a big deal but it can be when you're doing hundreds of thousands of watershed rasters. That's the "how to handle batch processing of multi images".

Yep, OK that sort of progressive writing doesn't sound like something a VRT would be intended to solve.

**Comment by richpsharp** [comment]
Okay wow look at that VRT Derived Band! Never heard of it and I will check it out. But also, I've never been able to get `gdal.BuildVRT` to work directly in the sense when I call it there are no errors and no results. I don't know what's going there and have no way to debug... turning on exceptions doesn't do anything either. When I have used it I've called through to the `gdalbuildvrt` command and it's worked. Have you ever gotten `gdal.BuildVRT` to work?

**Comment by phargogh** [comment]
I have!  Pygeoprocessing's [D8 Watershed Delineation uses a VRT](https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/routing/watershed.pyx#L903) to limit the size of the raster that needs to be polygonized.

The case above when I mentioned having used a VRT to stitch rasters, I had used the [command-line `gdalbuildvrt` tool](https://gdal.org/programs/gdalbuildvrt.html), which worked great.
