### ISSUE TITLE
ensure convolve_2d warns if a raster is not square blocks

### ISSUE THREAD

**Issue by richpsharp** [natcap/pygeoprocessing#168]
Just unrolled a very very very slow data pipeline that was occuring because the base raster had a blocksize of 126000x1. Convolve 2d moves little windows around and this was thrashing the gdal cache in a way that it was the only operation happening. I didn't spot it except to `gdalinfo` it, so convolve 2d should warn if this might happen.

**Comment by dcdenu4** [comment]
Interesting!
