### ISSUE TITLE
Revert new create_raster_from_vector_extent behavior?

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#198]
The changes in [this commit](https://github.com/natcap/pygeoprocessing/commit/d1941307a93324fe655bec4add3ac369da4a56a0) changed the behavior of `create_raster_from_vector_extent` beyond just improving the error message in #149. `layer.GetExtent()` does not always return the same value as what you get by merging the results of `feature.GetGeometryRef().GetEnvelope()` for each feature. The GDAL docs [say](https://gdal.org/python/osgeo.ogr.Layer-class.html#GetExtent) _"If bForce is TRUE (the default) then some implementations will actually scan the entire layer once to compute the MBR of all the features in the layer."_ So it sounds like it's not guaranteed to be the same, and may be less precise.

Unless getting the extent of each feature was too slow, I'm inclined to revert that change. @richpsharp does that sound okay?

This is a breaking change for one InVEST wind energy test. The difference is apparent with the `wind_energy_points.shp` output. Minimal example:
```
from osgeo import gdal

vector_path = '/Users/emily/Documents/wind_energy_workspace/output/wind_energy_points.shp'
vector = gdal.OpenEx(vector_path, gdal.OF_VECTOR)

shp_extent_a = None
shp_extent_b = None
for layer_index in range(vector.GetLayerCount()):
    layer = vector.GetLayer(layer_index)

    # Old method
    for feature in layer:
        # envelope is [xmin, xmax, ymin, ymax]
        feature_extent = feature.GetGeometryRef().GetEnvelope()
        if shp_extent_a is None:
            shp_extent_a = list(feature_extent)
        else:
            # expand bounds of current bounding box to include that
            # of the newest feature
            shp_extent_a = [
                f(shp_extent_a[index], feature_extent[index])
                for index, f in enumerate([min, max, min, max])]

    # New method
    if layer.GetFeatureCount() == 0:
        continue
    layer_extent = layer.GetExtent()
    if shp_extent_b is None:
        shp_extent_b = list(layer_extent)
    else:
        # expand bounds of current bounding box to include that
        # of the newest feature
        shp_extent_b = [
            f(shp_extent_b[index], layer_extent[index])
            for index, f in enumerate([min, max, min, max])]
    layer = None


print('extent by features:', shp_extent_a)
print('extent by layer:', shp_extent_b)
```
prints out
```
extent by features: [-96.66665649414062, -64.26648712158203, 17.4666805267334, 44.60015106201172]
extent by layer: [-96.66665649414062, 0.0, 0.0, 44.60015106201172]
```

**Comment by richpsharp** [comment]
Oh jeez, yeah that's not right. Sure, lets revert it!
