### ISSUE TITLE
distance_to_channel_mfd producing negative values

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#199]
And they're not just the nodata value.
Minimal example to reproduce, using the flow direction and streams rasters from NDR test data intermediate outputs:
```
import numpy
import pygeoprocessing
import pygeoprocessing.routing

flow_dir_path = '/Users/emily/Documents/ndr_test_wksp/intermediate_outputs/flow_direction.tif'
streams_path = '/Users/emily/Documents/ndr_test_wksp/intermediate_outputs/stream.tif'
target_path = '/Users/emily/Documents/demo_distance_to_stream_bug.tif'

pygeoprocessing.routing.distance_to_channel_mfd(
    (flow_dir_path, 1),
    (streams_path, 1),
    target_path)

arr = pygeoprocessing.raster_to_numpy_array(target_path)
nodata = pygeoprocessing.get_raster_info(target_path)['nodata'][0]
valid_mask = ~numpy.isclose(arr, nodata)
print(numpy.where(arr[valid_mask] < 0))
print(arr[valid_mask][arr[valid_mask] < 0])
```
```
$ python demo.py 
(array([17765, 17766, 17792, 17847, 17848, 17849, 17850, 17851, 17862,
       17863, 17864, 17865]),)
[-0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857
 -0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857 -0.07142857]
```

**Comment by richpsharp** [comment]
Hi @emlys, can you link the flow dir and streams path rasters somewhere that I could inspect them?

**Comment by richpsharp** [comment]
Given the sample data I'd like to also look at the DEM that was used to create the MFD raster -- it appears to have loops in the bottom, so it's possible the bug is in MFD routing not necessarily distance to stream: 
![image](https://user-images.githubusercontent.com/7773490/119569428-94281980-bd63-11eb-95d6-4db8e9799f9a.png)

**Comment by emlys** [comment]
I'm seeing those pixels are 1178599424 or `0100 0110 0100 0000 0000 0000 0000 0000`, so they're flowing into neighbors 5, 6, 7 off the bottom edge?
