### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#20]
Python 3.8 was released in December, 2019.  We should add Python 3.8 tests to our test suite and make sure that everything works as expected.

- [x] Add tests for Python 3.8 to github actions
- [x] Note 3.8 support in `setup.py`
- [x] Note the additional support in `HISTORY.rst`

**Comment by dcdenu4** [comment]
I was able to get a Python 3.8, Gdal < 3 environment set up using conda. All the tests for pygeoprocessing passed calling `pytest tests`. When pushing to pygeo, I realized that pygeo grabs gohlke specific versions of gdal to install, and there is no Python 3.8, GDAL < 3 version. So although I think a Python 3.8, Gdal < 3 version would work, I'm not sure how to implement the setup through the build process. So, focusing on GDAL 3.0 support.

**Comment by dcdenu4** [comment]
@davemfish I was wondering if we could get a Shapely version that works with Python 3.8. up on the natcap pypi simple path? I know you just worked through an issue pointing Windows Shapely, so I thought I'd ping you. Gohlke doesn't seem to be hosting any at the moment, but somehow I have one downloaded for Shapely 1.6.4 py38, 64 bit...

**Comment by davemfish** [comment]
@dcdenu4 I think @phargogh can hook us up with an update to the natcap package index if that's what we need. It looks like Gohlke has the cp38 shapely 1.7.0, but it's not synced to our index yet.

**Comment by phargogh** [comment]
@dcdenu4 @davemfish Yep!  It turns out that the wheels had already been uploaded to the bucket but the html index hadn't been synced.  This has been updated.

**Comment by richpsharp** [comment]
@phargogh , I reclassified this as a `task` since it doesn't affect any functionality.

**Comment by richpsharp** [comment]
Hey @dcdenu4, can you update this issue with whatever the status is? Are you still working on it? I'm happy to take it if you're unable to prioritize it now.

**Comment by dcdenu4** [comment]
I believe I have a branch that is ready to go for this now that GDAL 3 has been sorted out. I'll jump on this.

**Comment by dcdenu4** [comment]
This was already done and included in PR #50
