### ISSUE TITLE
distance_to_channel_mfd still factors in distance to edge

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#214]
I suspect that the fix to #171 is not doing quite what we want. Pixels that don't drain to a stream at all are `nodata`, as expected. But pixels that have only part of their flow drain to a stream are still defined.

As I understand it `dist_to_channel_mfd` is weighted by the proportion of flow in each direction. Like it's the average distance to a stream, not the shortest. And it appears that the portions flowing off the edge or into nodata are getting a distance of 0.  I made a diagram to help keep track of what I was looking at 😄 
![image](https://user-images.githubusercontent.com/43770515/129120022-f2c5a624-094c-46d1-b88f-56056dd47dde.png)

**Comment by dcdenu4** [comment]
Great mock up of the problem Emily. So, is the problem that we want those partial flow pixels to be defined, but they are not obtaining the correct distance to channel? The distance to channel they are getting is to the edge?

**Comment by emlys** [comment]
Yeah, I think they're getting the distance to the edge when that should be ignored. Two possible ways to handle this case:
1. Set any pixel that partially drains out of the watershed to nodata. Only define `distance_to_channel` for pixels where 100% of their water drains to a stream. (this would probably take out big chunks of the watershed, because it would apply recursively upstream: any pixel that drains to any pixel that drains to any pixel... that drains out of the watershed would be nodata)
2. Only count the distance traveled by the fraction of flow that reaches a stream. In the example above, it would be the `distance_to_channel` for just that 1/16th of the water flowing in the bottom-left direction. I like this option but would need to be clear that it's only the distance *in the context of this watershed* and make sure that works with the SDR/NDR equations.
