### ISSUE TITLE
reclassify_raster does not allow for nodata reclassification

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#220]
When we updated `reclassify_raster` to properly deal with float `nodata` values by masking them out, we inadvertently took away the ability to reclassify `nodata` values. This came to light when crop production tests failed, the only model to attempt such a thing. https://github.com/natcap/invest/pull/555#issuecomment-908554778

In a discussion I think it was the general consensus that this function should have that ability as it could be useful from a scripting point of view and the function itself should explicitly handle `nodata` cases where it might also appear in the map.

**Comment by phargogh** [comment]
Released in pygeoprocessing 2.3.2.
