### ISSUE TITLE
Add error message details in convolve_2d

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#228]
An InVEST user recently came across the row based blocksize error in `convolve_2d`. The error message just defaults to reporting that the `signal_path_band` is the culprit, when in fact it can be the `kernel_path_band`.

**Comment by phargogh** [comment]
Fun!  @dcdenu4 could you include a link to the thread where this occurred?

**Comment by dcdenu4** [comment]
Sure can, here is the forum post: https://community.naturalcapitalproject.org/t/row-blocksize-error/2337/4
