### ISSUE TITLE
Remove x86 windows wheels from the build workflow?

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#232]
We still build x86 wheels for windows, but it's unclear if these are actually useful.  InVEST is now an x64 binary and even `conda-forge` has stopped building x86 packages.  Here are a few questions that come to mind that are worth considering:

* Does anyone at natcap still use x86 python who needs to use pygeoprocessing?
* How do the PyPI download stats for the x86 pygeoprocessing wheels compare to the x64 wheels?  [PyPInfo](https://github.com/ofek/pypinfo/blob/master/README.rst) looks useful for this.

**Comment by dcdenu4** [comment]
I came across this: https://pepy.tech/project/pygeoprocessing, but unfortunately they don't break anything down by architecture. This one is fun too: https://pypistats.org/packages/pygeoprocessing

**Comment by phargogh** [comment]
I hastily moved this to the 2.3.5 milestone, but it deserves looking at the PyPI bigquery statistics.  I'll bump to the next minor release.

**Comment by phargogh** [comment]
OK!  So this was pretty fun to dig into and `pypinfo` has been really, really useful in determining that we have had trivially few 32-bit pygeoprocessing installs _ever_.

<details>
<summary>Click to see markdown-formatted PyPI report</summary>

The table below is the output of the following `pypinfo` command:

```
$ pypinfo --markdown --limit=500 --start-date="2021-01-01" --end-date="2022-12-12" pygeoprocessing file
```

In summary, in the past 2 years we have had a total of 136 win32 downloads, which is 0.28% of the total PyPI downloads.

You can verify this count with:
```
$ grep win32 foo.txt | awk  '{ print $4 }' | paste -sd+ - | bc
```

| file                                                            | download_count |
| --------------------------------------------------------------- | -------------: |
| pygeoprocessing-2.1.2.tar.gz                                    |          8,527 |
| pygeoprocessing-2.3.2-cp38-cp38-macosx_10_14_x86_64.whl         |          3,066 |
| pygeoprocessing-2.1.2-cp38-cp38-win_amd64.whl                   |          2,706 |
| pygeoprocessing-2.3.3.post0-cp39-cp39-win_amd64.whl             |          2,206 |
| pygeoprocessing-2.3.2-cp38-cp38-win_amd64.whl                   |          2,019 |
| pygeoprocessing-2.3.2-cp39-cp39-macosx_10_14_x86_64.whl         |          1,919 |
| pygeoprocessing-2.3.2-cp37-cp37m-macosx_10_14_x86_64.whl        |          1,891 |
| pygeoprocessing-2.3.2-cp39-cp39-win_amd64.whl                   |          1,880 |
| pygeoprocessing-2.3.2-cp37-cp37m-win_amd64.whl                  |          1,592 |
| pygeoprocessing-2.3.3.post0-cp38-cp38-win_amd64.whl             |          1,584 |
| pygeoprocessing-2.3.3.post0-cp38-cp38-macosx_10_14_x86_64.whl   |          1,564 |
| pygeoprocessing-2.3.3.post0-cp39-cp39-macosx_10_15_x86_64.whl   |          1,541 |
| pygeoprocessing-2.3.3.post0.tar.gz                              |          1,120 |
| pygeoprocessing-2.3.2.tar.gz                                    |          1,078 |
| pygeoprocessing-2.3.3.post0-cp37-cp37m-win_amd64.whl            |          1,035 |
| pygeoprocessing-2.3.3.post0-cp310-cp310-win_amd64.whl           |          1,000 |
| pygeoprocessing-2.3.4-cp310-cp310-win_amd64.whl                 |            869 |
| pygeoprocessing-2.3.3.post0-cp37-cp37m-macosx_10_14_x86_64.whl  |            760 |
| pygeoprocessing-2.3.3.post0-cp310-cp310-macosx_10_15_x86_64.whl |            692 |
| pygeoprocessing-2.3.4-cp310-cp310-macosx_10_15_x86_64.whl       |            689 |
| pygeoprocessing-1.9.2.tar.gz                                    |            534 |
| pygeoprocessing-2.3.4.tar.gz                                    |            425 |
| pygeoprocessing-2.3.4-cp39-cp39-win_amd64.whl                   |            414 |
| pygeoprocessing-2.3.4-cp38-cp38-win_amd64.whl                   |            387 |
| pygeoprocessing-2.3.4-cp38-cp38-macosx_10_15_x86_64.whl         |            334 |
| pygeoprocessing-2.3.4-cp39-cp39-macosx_10_15_x86_64.whl         |            334 |
| pygeoprocessing-2.2.0.tar.gz                                    |            323 |
| pygeoprocessing-2.3.0.tar.gz                                    |            288 |
| pygeoprocessing-2.3.0-cp38-cp38-macosx_10_14_x86_64.whl         |            268 |
| pygeoprocessing-0.3.3.zip                                       |            249 |
| pygeoprocessing-2.1.0.tar.gz                                    |            193 |
| pygeoprocessing-2.2.0-cp38-cp38-win_amd64.whl                   |            187 |
| pygeoprocessing-2.3.0-cp38-cp38-win_amd64.whl                   |            178 |
| pygeoprocessing-2.3.0-cp37-cp37m-win_amd64.whl                  |            158 |
| pygeoprocessing-2.1.1.tar.gz                                    |            157 |
| pygeoprocessing-2.3.0-cp39-cp39-macosx_10_14_x86_64.whl         |            149 |
| pygeoprocessing-2.3.0-cp37-cp37m-macosx_10_14_x86_64.whl        |            145 |
| pygeoprocessing-2.3.0-cp39-cp39-win_amd64.whl                   |            142 |
| pygeoprocessing-2.2.0-cp37-cp37m-win_amd64.whl                  |            126 |
| pygeoprocessing-2.2.0-cp38-cp38-macosx_10_14_x86_64.whl         |            115 |
| pygeoprocessing-2.0.0.tar.gz                                    |            108 |
| pygeoprocessing-1.9.1.tar.gz                                    |            102 |
| pygeoprocessing-1.9.0.tar.gz                                    |            102 |
| pygeoprocessing-1.8.0.tar.gz                                    |            101 |
| pygeoprocessing-1.5.0.tar.gz                                    |             98 |
| pygeoprocessing-1.6.1.tar.gz                                    |             94 |
| pygeoprocessing-1.1.0.tar.gz                                    |             94 |
| pygeoprocessing-1.0.0.tar.gz                                    |             92 |
| pygeoprocessing-0.6.0.tar.gz                                    |             91 |
| pygeoprocessing-0.7.0.tar.gz                                    |             91 |
| pygeoprocessing-1.4.1.tar.gz                                    |             90 |
| pygeoprocessing-1.2.0.tar.gz                                    |             89 |
| pygeoprocessing-0.3.2.tar.gz                                    |             89 |
| pygeoprocessing-1.6.0.tar.gz                                    |             88 |
| pygeoprocessing-0.5.0.tar.gz                                    |             88 |
| pygeoprocessing-1.4.0.tar.gz                                    |             88 |
| pygeoprocessing-1.3.1.tar.gz                                    |             88 |
| pygeoprocessing-1.3.0.tar.gz                                    |             87 |
| pygeoprocessing-1.7.0.tar.gz                                    |             87 |
| pygeoprocessing-1.0.1.tar.gz                                    |             87 |
| pygeoprocessing-0.4.1.tar.gz                                    |             86 |
| pygeoprocessing-2.3.1.tar.gz                                    |             86 |
| pygeoprocessing-0.4.2.tar.gz                                    |             86 |
| pygeoprocessing-1.2.1.tar.gz                                    |             86 |
| pygeoprocessing-0.4.4.tar.gz                                    |             86 |
| pygeoprocessing-1.2.3.tar.gz                                    |             85 |
| pygeoprocessing-0.4.3.tar.gz                                    |             84 |
| pygeoprocessing-0.2.2.zip                                       |             84 |
| pygeoprocessing-0.3.1.zip                                       |             83 |
| pygeoprocessing-0.3.0.tar.gz                                    |             82 |
| pygeoprocessing-2.2.0-cp37-cp37m-macosx_10_14_x86_64.whl        |             73 |
| pygeoprocessing-2.3.3-cp38-cp38-win_amd64.whl                   |             54 |
| pygeoprocessing-2.3.1-cp38-cp38-macosx_10_14_x86_64.whl         |             54 |
| pygeoprocessing-2.3.3-cp38-cp38-macosx_10_14_x86_64.whl         |             52 |
| pygeoprocessing-2.3.3.tar.gz                                    |             50 |
| pygeoprocessing-2.3.3-cp39-cp39-win_amd64.whl                   |             49 |
| pygeoprocessing-0.1.1.zip                                       |             46 |
| pygeoprocessing-0.1.3.zip                                       |             46 |
| pygeoprocessing-0.1.6.zip                                       |             46 |
| pygeoprocessing-0.1.5.zip                                       |             46 |
| pygeoprocessing-0.1.8.zip                                       |             46 |
| pygeoprocessing-0.1.2.zip                                       |             45 |
| pygeoprocessing-0.2.0.zip                                       |             45 |
| pygeoprocessing-0.1.4.zip                                       |             44 |
| pygeoprocessing-0.2.1.zip                                       |             44 |
| pygeoprocessing-0.1.7.zip                                       |             43 |
| pygeoprocessing-2.3.1-cp38-cp38-win_amd64.whl                   |             36 |
| pygeoprocessing-2.3.3-cp37-cp37m-win_amd64.whl                  |             35 |
| pygeoprocessing-2.3.1-cp37-cp37m-win_amd64.whl                  |             31 |
| pygeoprocessing-1.9.2-cp37-cp37m-win_amd64.whl                  |             31 |
| pygeoprocessing-2.3.3-cp39-cp39-macosx_10_15_x86_64.whl         |             29 |
| pygeoprocessing-2.2.0-cp39-cp39-win_amd64.whl                   |             28 |
| pygeoprocessing-2.3.3-cp37-cp37m-macosx_10_14_x86_64.whl        |             28 |
| pygeoprocessing-2.3.1-cp39-cp39-win_amd64.whl                   |             28 |
| pygeoprocessing-2.3.1-cp39-cp39-macosx_10_14_x86_64.whl         |             24 |
| pygeoprocessing-2.3.1-cp37-cp37m-macosx_10_14_x86_64.whl        |             24 |
| pygeoprocessing-0.3.3-cp27-cp27m-win32.whl                      |             24 |
| pygeoprocessing-1.9.2-cp36-cp36m-win_amd64.whl                  |             21 |
| pygeoprocessing-2.3.4-cp37-cp37m-win_amd64.whl                  |             20 |
| pygeoprocessing-0.3.0a7.zip                                     |             19 |
| pygeoprocessing-2.1.1-cp37-cp37m-win_amd64.whl                  |             16 |
| pygeoprocessing-2.2.0-cp39-cp39-macosx_10_14_x86_64.whl         |             15 |
| pygeoprocessing-2.1.1-cp38-cp38-win_amd64.whl                   |             11 |
| pygeoprocessing-2.0.0-cp37-cp37m-win_amd64.whl                  |             11 |
| pygeoprocessing-0.3.0a12.zip                                    |             11 |
| pygeoprocessing-0.3.0a15.zip                                    |              9 |
| pygeoprocessing-0.3.0a17.zip                                    |              9 |
| pygeoprocessing-0.3.0a3.zip                                     |              8 |
| pygeoprocessing-1.8.1rc1.tar.gz                                 |              8 |
| pygeoprocessing-0.3.0a5.zip                                     |              7 |
| pygeoprocessing-0.3.0a20.zip                                    |              7 |
| pygeoprocessing-0.3.0a19.zip                                    |              7 |
| pygeoprocessing-0.3.0a8.zip                                     |              7 |
| pygeoprocessing-0.3.0a22.zip                                    |              7 |
| pygeoprocessing-0.3.0a21.zip                                    |              7 |
| pygeoprocessing-0.3.0a9.zip                                     |              7 |
| pygeoprocessing-0.3.0a6.zip                                     |              7 |
| pygeoprocessing-0.3.0a18.zip                                    |              7 |
| pygeoprocessing-0.3.0a10.zip                                    |              6 |
| pygeoprocessing-0.3.0a11.zip                                    |              6 |
| pygeoprocessing-2.3.4-cp37-cp37m-macosx_10_15_x86_64.whl        |              6 |
| pygeoprocessing-0.1.0.dev68.zip                                 |              6 |
| pygeoprocessing-0.3.0a14.zip                                    |              6 |
| pygeoprocessing-0.3.0a4.zip                                     |              6 |
| pygeoprocessing-0.1.1.dev5.zip                                  |              6 |
| pygeoprocessing-0.3.0a2.zip                                     |              5 |
| pygeoprocessing-0.1.0.dev71.zip                                 |              5 |
| pygeoprocessing-0.3.0a13.zip                                    |              5 |
| pygeoprocessing-2.3.3.post0-cp37-cp37m-win32.whl                |              5 |
| pygeoprocessing-0.1.2.dev1.zip                                  |              5 |
| pygeoprocessing-2.0.0-cp38-cp38-macosx_10_14_x86_64.whl         |              4 |
| pygeoprocessing-0.3.0a16.zip                                    |              4 |
| pygeoprocessing-2.0.0-cp37-cp37m-win32.whl                      |              4 |
| pygeoprocessing-0.4.0a1.tar.gz                                  |              4 |
| pygeoprocessing-1.7.0-cp37-cp37m-win_amd64.whl                  |              4 |
| pygeoprocessing-1.9.2-cp37-cp37m-win32.whl                      |              4 |
| pygeoprocessing-0.4.0a2.tar.gz                                  |              3 |
| pygeoprocessing-2.3.2-cp38-cp38-win32.whl                       |              3 |
| pygeoprocessing-1.8.0-cp37-cp37m-win_amd64.whl                  |              3 |
| pygeoprocessing-1.9.1-cp37-cp37m-win_amd64.whl                  |              3 |
| pygeoprocessing-2.3.3.post0-cp38-cp38-win32.whl                 |              3 |
| pygeoprocessing-2.1.0-cp38-cp38-win_amd64.whl                   |              3 |
| pygeoprocessing-2.0.0-cp37-cp37m-macosx_10_14_x86_64.whl        |              3 |
| pygeoprocessing-1.9.0-cp37-cp37m-win_amd64.whl                  |              3 |
| pygeoprocessing-1.9.2-cp36-cp36m-win32.whl                      |              3 |
| pygeoprocessing-2.3.0-cp37-cp37m-win32.whl                      |              2 |
| pygeoprocessing-2.0.0-cp38-cp38-win_amd64.whl                   |              2 |
| pygeoprocessing-2.3.3-cp310-cp310-macosx_10_15_x86_64.whl       |              2 |
| pygeoprocessing-1.8.1rc1-cp37-cp37m-win_amd64.whl               |              2 |
| pygeoprocessing-2.3.0-cp39-cp39-win32.whl                       |              2 |
| pygeoprocessing-1.9.0-cp36-cp36m-win32.whl                      |              2 |
| pygeoprocessing-2.3.4-cp37-cp37m-win32.whl                      |              2 |
| pygeoprocessing-1.9.0-cp37-cp37m-win32.whl                      |              2 |
| pygeoprocessing-1.9.0-cp36-cp36m-win_amd64.whl                  |              2 |
| pygeoprocessing-2.3.3-cp310-cp310-win_amd64.whl                 |              2 |
| pygeoprocessing-2.3.2-cp39-cp39-win32.whl                       |              2 |
| pygeoprocessing-2.2.0-cp38-cp38-win32.whl                       |              2 |
| pygeoprocessing-2.3.0-cp38-cp38-win32.whl                       |              2 |
| pygeoprocessing-2.3.2-cp37-cp37m-win32.whl                      |              2 |
| pygeoprocessing-2.3.1-cp39-cp39-win32.whl                       |              2 |
| pygeoprocessing-2.3.3.post0-cp39-cp39-win32.whl                 |              2 |
| pygeoprocessing-1.2.3-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a4-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-1.4.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-2.3.3-cp310-cp310-win32.whl                     |              1 |
| pygeoprocessing-1.9.1-cp37-cp37m-win32.whl                      |              1 |
| pygeoprocessing-2.2.0-cp39-cp39-win32.whl                       |              1 |
| pygeoprocessing-0.3.0a6-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-0.1.7-cp27-none-win32.whl                       |              1 |
| pygeoprocessing-2.3.1-cp38-cp38-win32.whl                       |              1 |
| pygeoprocessing-1.4.0-py2.7-win32.egg                           |              1 |
| pygeoprocessing-0.7.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-2.3.3-cp39-cp39-win32.whl                       |              1 |
| pygeoprocessing-0.3.0a7-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-1.0.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.6.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a9-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-0.3.0a3-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-0.3.0a5-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-1.3.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a15-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.3.0a13-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-1.2.3-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.5.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.4.0a2-cp27-cp27m-win32.whl                    |              1 |
| pygeoprocessing-1.8.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.2.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.4.2-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.2.1-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-0.3.0a14-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.3.0a22-cp27-cp27m-win32.whl                   |              1 |
| pygeoprocessing-1.3.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-2.3.4-cp310-cp310-win32.whl                     |              1 |
| pygeoprocessing-1.5.0-py3.6-win-amd64.egg                       |              1 |
| pygeoprocessing-1.9.1-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-0.3.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.1.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-0.2.2-cp27-none-win32.whl                       |              1 |
| pygeoprocessing-1.6.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-2.3.3-cp37-cp37m-win32.whl                      |              1 |
| pygeoprocessing-1.2.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.2.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.2-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.4.4-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.1.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.5.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.6.1-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.0.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a8-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-2.3.3-cp38-cp38-win32.whl                       |              1 |
| pygeoprocessing-1.8.1rc1-cp36-cp36m-win_amd64.whl               |              1 |
| pygeoprocessing-0.3.0a2-cp27-none-win32.whl                     |              1 |
| pygeoprocessing-0.3.0a20-cp27-cp27m-win32.whl                   |              1 |
| pygeoprocessing-0.5.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.9.1-cp36-cp36m-win32.whl                      |              1 |
| pygeoprocessing-1.6.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.4.1-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-2.2.0-cp37-cp37m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a19-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.3.0a16-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.3.0a18-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-1.4.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.3.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-1.2.3-py2.7-win32.egg                           |              1 |
| pygeoprocessing-2.3.3.post0-cp310-cp310-win32.whl               |              1 |
| pygeoprocessing-0.1.8-cp27-none-win32.whl                       |              1 |
| pygeoprocessing-2.3.4-cp39-cp39-win32.whl                       |              1 |
| pygeoprocessing-0.3.0a12-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.6.0-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-2.3.1-cp37-cp37m-win32.whl                      |              1 |
| pygeoprocessing-0.2.0-cp27-none-win32.whl                       |              1 |
| pygeoprocessing-0.3.0a10-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-0.4.3-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-1.3.1-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-0.3.0a11-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-1.4.0-cp36-cp36m-win_amd64.whl                  |              1 |
| pygeoprocessing-0.2.1-cp27-none-win32.whl                       |              1 |
| pygeoprocessing-0.4.1-cp27-cp27m-win32.whl                      |              1 |
| pygeoprocessing-0.3.0a17-cp27-none-win32.whl                    |              1 |
| pygeoprocessing-2.0.0-cp38-cp38-win32.whl                       |              1 |
| pygeoprocessing-2.3.4-cp38-cp38-win32.whl                       |              1 |
| pygeoprocessing-0.3.0a21-cp27-cp27m-win32.whl                   |              1 |
| pygeoprocessing-0.4.0a1-cp27-cp27m-win32.whl                    |              1 |
| Total                                                           |         47,101 |
</details>

`condastats` doesn't even list `win32` packages as a build target, though it isn't clear if this is because win32 records have been purged or if we never had any downloads at all:

```
$ condastats pkg_platform --start_month=2020-01 --end_month=2022-11 pygeoprocessing
pkg_name         pkg_platform
pygeoprocessing  win-64           7915
                 linux-64        21029
                 osx-64           4577
Name: counts, dtype: int64
```

So, in summary, I'll be pulling the win32 builds entirely in a forthcoming PR.
