### ISSUE TITLE
Proposal: `raster_calculator` wrapper

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#235]
Proposal for a higher-level version of `raster_calculator` that abstracts away some details of working with rasters and arrays. The goal would be to be able to do arithmetic with rasters and scalars interchangeably, like how `numpy` lets you use arrays and scalars interchangeably.

This would abstract away:
* masking out results where any input is nodata
* details of calling `raster_calculator`: indicating the band of each raster, and marking scalar values as `'raw'`
* (optionally) choosing an output dtype
* (optionally) choosing an output nodata value

## Justification
For #234, I skimmed through the models and found that pixelwise multiplication and addition are reimplemented in several models.

I also counted over 3 dozen functions that use `raster_calculator` to do multi-part arithmetic operations on rasters (e.g., adding two rasters pixelwise, then multiplying by a scalar). These functions are highly similar and the unique logic usually comes down to one line of array math. The rest is taken up by reading and comparing nodata values, masking, and calling `raster_calculator`.

So a solution for #234 that _also_ handles other, or combinations of, pixelwise arithmetic, could save a lot more repeated code (vs. making individual functions for the most-used operations).

## Signature and docstring for proposed function
```
def raster_calculator_2(op, *inputs, target_path='', target_nodata=None, 
                      target_dtype=None):
    """
    Apply a pixelwise function to a series of raster and/or scalar inputs.

    The output raster will have nodata where any input raster has nodata.
    Raster inputs are split into aligned blocks, and the function is 
    applied individually to each stack of blocks (as numpy arrays). 

    Args:
        op (function): Function to apply to the inputs. It should accept a 
            number of arguments equal to the length of ``*inputs``. It should 
           return a numpy array with the same shape as its array input(s).
        *inputs: Strings (raster paths) and/or scalar inputs to ``op``, in the 
            order that they will be passed to ``op``. All raster inputs 
            should be aligned and have the same dimensions. At least one input 
            must be a raster. 
        target_path (str): path to write out the output raster.
        target_nodata (number): Nodata value to use for the output raster. 
            Optional. If not provided, a suitable nodata value will be chosen.
        target_dtype (numpy.dtype): dtype to use for the output. Optional. If 
            not provided, a suitable dtype will be chosen.

    Returns:
        ``None``
```
_Note: A suitable dtype could be chosen by taking the most precise dtype of all inputs, so that no information is lost.
A suitable nodata value could be derived from the dtype. See also natcap/invest#783._

#### With existing `raster_calculator`
```
def _calculate_npv(delta_carbon_path, valuation_constant, npv_out_path):
    """Calculate net present value.

    Args:
        delta_carbon_path (string): path to change in carbon storage over
            time.
        valuation_constant (float): value to multiply each carbon storage
            value by to calculate NPV.
        npv_out_path (string): path to output net present value raster.

    Returns:
        None.
    """
    def _npv_value_op(carbon_array):
        """Calculate the NPV given carbon storage or loss values."""
        result = numpy.empty(carbon_array.shape, dtype=numpy.float32)
        result[:] = _VALUE_NODATA
        valid_mask = ~utils.array_equals_nodata(carbon_array,  _CARBON_NODATA)
        result[valid_mask] = carbon_array[valid_mask] * valuation_constant
        return result

    pygeoprocessing.raster_calculator(
        [(delta_carbon_path, 1)], _npv_value_op, npv_out_path,
        gdal.GDT_Float32, _VALUE_NODATA)

_calculate_npv(delta_carbon_path, valuation_constant, npv_out_path)
```
#### With proposed function
```
raster_calculator_2(lambda d, v: d * v, delta_carbon_path, valuation_constant,
                    target_path=npv_out_path)
```
#### With existing `raster_calculator`
```
def _sum_rasters(storage_path_list, output_sum_path):
    """Sum all the rasters in `storage_path_list` to `output_sum_path`."""
    def _sum_op(*storage_arrays):
        """Sum all the arrays or nodata a pixel stack if one exists."""
        valid_mask = reduce(
            lambda x, y: x & y, [
                ~utils.array_equals_nodata(_, _CARBON_NODATA)
                for _ in storage_arrays])
        result = numpy.empty(storage_arrays[0].shape)
        result[:] = _CARBON_NODATA
        result[valid_mask] = numpy.sum([
            _[valid_mask] for _ in storage_arrays], axis=0)
        return result

    pygeoprocessing.raster_calculator(
        [(x, 1) for x in storage_path_list], _sum_op, output_sum_path,
        gdal.GDT_Float32, _CARBON_NODATA)

_sum_rasters(storage_path_list, output_sum_path)
```

#### With proposed function
```
raster_calculator_2(lambda *xs: numpy.sum(xs, axis=0),
    *storage_path_list, target_path=output_sum_path
```

#### With existing `raster_calculator`
```
def _calculate_ndr(
        effective_retention_path, ic_factor_path, k_param, target_ndr_path):
    """Calculate NDR as a function of Equation 4 in the user's guide."""
    ic_factor_raster = gdal.OpenEx(ic_factor_path, gdal.OF_RASTER)
    ic_factor_band = ic_factor_raster.GetRasterBand(1)
    ic_min, ic_max, _, _ = ic_factor_band.GetStatistics(0, 1)
    ic_factor_band = None
    ic_factor_raster = None
    ic_0_param = (ic_min + ic_max) / 2.0
    effective_retention_nodata = pygeoprocessing.get_raster_info(
        effective_retention_path)['nodata'][0]
    ic_nodata = pygeoprocessing.get_raster_info(ic_factor_path)['nodata'][0]

    def _calculate_ndr_op(effective_retention_array, ic_array):
        """Calculate NDR."""
        valid_mask = (
            ~utils.array_equals_nodata(
                effective_retention_array, effective_retention_nodata) &
            ~utils.array_equals_nodata(ic_array, ic_nodata))
        result = numpy.empty(valid_mask.shape, dtype=numpy.float32)
        result[:] = _TARGET_NODATA
        result[valid_mask] = (
            (1.0 - effective_retention_array[valid_mask]) /
            (1.0 + numpy.exp(
                (ic_0_param - ic_array[valid_mask]) / k_param)))
        return result

    pygeoprocessing.raster_calculator(
        [(effective_retention_path, 1), (ic_factor_path, 1)],
        _calculate_ndr_op, target_ndr_path, gdal.GDT_Float32, _TARGET_NODATA)

_calculate_ndr(effective_retention_path, ic_factor_path, k_param, target_ndr_path)
```
#### With proposed function
```
# NOTE: raster min and max can't be calculated for each block independently
# thus it can't be done with raster_calculator or raster_calculator_2
ic_factor_raster = gdal.OpenEx(ic_factor_path, gdal.OF_RASTER)
ic_factor_band = ic_factor_raster.GetRasterBand(1)
ic_min, ic_max, _, _ = ic_factor_band.GetStatistics(0, 1)
ic_factor_band = None
ic_factor_raster = None
ic_0_param = (ic_min + ic_max) / 2.0

raster_calculator_2(
    lambda eff, ic_0, ic, k: (1 - eff) / (1 + numpy.exp((ic_0 - ic) / k))
    effective_retention_path, ic_0_param, ic_factor_path, k_param, 
    target_path=target_ndr_path)
```

**Comment by phargogh** [comment]
Thanks for raising this issue @emlys !  I fully support factoring out all of this repetitive nodata code that we use over and over in InVEST and it'd be nice to have a more succinct way to express these pixel-stack functions.

I think a lot of relevant functionality exists now in `pygeoprocessing.symbolic.evaluate_raster_calculator_expression` (https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/symbolic.py#L14), at least in terms of the mutual-masking of nodata values.

I particularly like that this is proposing using a python callable directly.  Because of this, this approach allows us a few advantages over the current symbolic approach:
* `eval` supports only a subset of the language: expressions.  Conditions are not supported.  By contrast, callables would allow us to use the full power of the language, including by accessing compiled cython functions if needed.
* Callables don't need to be re-`eval`'ed for each raster block
* We get around any potential security worries about accepting user-defined text strings and `eval`ing them (not that we're usually doing that in an online context)

>         *inputs: Strings (raster paths) and/or scalar inputs to ``op``, in the 
>          order that they will be passed to ``op``. All raster inputs 
>          should be aligned and have the same dimensions. At least one input 
>          must be a raster. 
One comment that I have is that if we're providing a python callable, I wonder if we'd be able to simply expect that the scalar is used directly within the callable.  If we're defining a lambda, for example, there's be no need to pass another variable, we can simply use it directly.

**Comment by emlys** [comment]
@phargogh thanks for pointing out `pygeoprocessing.symbolic.evaluate_raster_calculator_expression`, I hadn't seen it before. I'm curious if there was some reason that it takes an expression rather than a function? There's a comment in there _"As far as we can tell, the benefits of being able to evaluate these sorts of expressions will outweight the risks"_. Are there benefits of an expression vs. a callable that I'm missing?

I don't see `pygeoprocessing.symbolic.evaluate_raster_calculator_expression` used anywhere in pygeoprocessing or invest. Do you know if it's used somewhere else?

> One comment that I have is that if we're providing a python callable, I wonder if we'd be able to simply expect that the scalar is used directly within the callable. If we're defining a lambda, for example, there's be no need to pass another variable, we can simply use it directly.

Very good point!

**Comment by emlys** [comment]
I'm working on a draft implementation in https://github.com/emlys/pygeoprocessing/tree/task/235.

**Comment by phargogh** [comment]
> I'm curious if there was some reason that it takes an expression rather than a function? There's a comment in there "As far as we can tell, the benefits of being able to evaluate these sorts of expressions will outweight the risks". Are there benefits of an expression vs. a callable that I'm missing?

The intent with this function was to expose the pixelwise math (which is often a simple mathematical expression) to a science user.  I for sure remember that Becky took this and ran with it in a number of other scripts/programs since she no longer had to worry about trying to translate something into numpy and worry about masking and such.  An expression allowed for Becky types to be able to just define the math, define the variables, and then have the function do the rest.  With a callable, there's more code to write ... even with a lambda, you still need to define parameters before they can be used.

In truth, it's very possible that an expression is all that is needed, though maybe it needs to be modified to support namespaces like `math.e` and/or `numpy.exp`.

> I don't see `pygeoprocessing.symbolic.evaluate_raster_calculator_expression` used anywhere in pygeoprocessing or invest. Do you know if it's used somewhere else?

BCK and RS were using it in some of their other work, and I for sure see a use of it in the NCI NDR code (sorry, it's in a private repo that I don't control).

**Comment by emlys** [comment]
Continuing discussion of this in a [design doc](https://docs.google.com/document/d/1tc5dgAUShY4s6uWzP439Sdp6td3qeXrFpn_r8gjqEio/edit#).

**Comment by emlys** [comment]
If we end up with a function called `raster_reduce` from https://github.com/natcap/pygeoprocessing/issues/285, I'd suggest calling this function `raster_map`.

**Comment by emlys** [comment]
We approved this proposal on the coffee call today
