### ISSUE TITLE
do release 2.3.3

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#238]
The main purpose of this release will be to have the numpy versions pinned in pyproject.toml so that it's compatible with invest. Needed for https://github.com/natcap/invest.users-guide/issues/62.

**Comment by SchroeterJan** [comment]
I just ran into an issue installing pygeoprocessing using pip:

ERROR: pygeoprocessing from https://files.pythonhosted.org/packages/4d/73/dad89a36119b3bed4a0e588c3db893bf0da9b5e2e4d2627851f89f88b79f/pygeoprocessing-2.3.3.tar.gz#sha256=07948706b30a06998badb3ec6c4de3ad00f9f8e756743f17eaae3b04dbc95ca5 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by phargogh** [comment]
@SchroeterJan we're working on it!

A short-term workaround would be to install from git, `pip install "git+https://github.com/natcap/pygeoprocessing.git@2.3.3"` if you'd like the latest released version.

**Comment by SchroeterJan** [comment]
Wow, super quick response! No worries, just wanted to reach out
Went for 2.3.2, seems all good

**Comment by emlys** [comment]
@SchroeterJan 2.3.3.post0 is now up on PyPI and 2.3.3 has been yanked.
