### ISSUE TITLE
Remove python2 compatibility things from pygeoprocessing

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#24]
Pygeoprocessing still has a few things left over from when we were trying to have the package be cross-compatible with `python2` and `python3`, things like the `future` dependency and a few conditional imports (like `Queue` being in different places).  Now that we're python3-only, we should clean these things up.

Known parts to this:
- [x] `mock` --> `unittest.mock`
- [x] Remove `future` from `requirements.txt`
- [x] Remove `future` and `future`-defined imports (`builtins`, others?) throughout the package

**Comment by phargogh** [comment]
Actually, these things are better suited to a bugfix release.

**Comment by richpsharp** [comment]
hey @dcdenu4, can you update your status on this too? I'm happy to take it!

**Comment by dcdenu4** [comment]
@richpsharp I don't think this issue has been formally addressed yet, though it does look like `mock` was refactored to use `unittest.mock`. But I still see `future` and some `python 2` comments kicking about.

If you're feeling motivated to get after this by all means go ahead. It's a bit low in my stack at the moment. But would probably finish this by end of week. So, that's the status update!
