### ISSUE TITLE
Windows tests crash with shapely 1.7.0

### ISSUE THREAD

**Issue by davemfish** [natcap/pygeoprocessing#25]
Shapely 1.7.0 was just released and we're seeing a variety of issues. I triggered the Actions test suite with a dummy commit over in my fork and observed errors like `ValueError: GEOSGeom_createLinearRing_r returned a NULL pointer` on Windows . 

See full logs here:
https://github.com/davemfish/pygeoprocessing/runs/418379492?check_suite_focus=true

Shapely does not describe any backwards incompatibility with this release, so presumably these are bugs that will be fixed by shapely. Probably the thing to do in the meantime is avoid `shapely 1.7.0`

**Comment by davemfish** [comment]
resolved by #26

**Comment by davemfish** [comment]
Re-opening because we have a better solution than avoiding this version of shapely entirely. We need only avoid a certain build on a certain PyPI.

**Comment by dcdenu4** [comment]
@davemfish I posted to the Python 3.8 issue, but thought I'd bring it back over here. For Python 3.8 support we'll need a version of Shapely to match and it doesn't look like Golhke is hosting any at the moment. I just installed the `Shapely‑1.7.0‑cp38‑cp38‑win_amd64.whl` (I'm running Windows Python 3.8 64-bit) and all the Pygeo tests pass for me. I wonder if the dll issues have been sorted?

**Comment by davemfish** [comment]
@dcdenu4 , it looks that whl for 3.8 is available from Gohlke. And in the end we figured out that it was only the 1.7.0 wheels on PyPI that were problematic. The Gohlke builds worked all along, it was just a matter of making sure pip installed them instead of the ones from PyPI.
