### ISSUE TITLE
Optionally allow touching but nonoverlapping polygons in `calculate_disjoint_polygon_set`

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#269]
In working on Urban Nature Access, we had a case where we had a large cluster of polygons with boundaries that touched but whose interiors were all distinct.  Using the current implementation of `calculate_disjoint_polygon_set`, there were 8 groupings of polygons. I propose including an optional flag in `calculate_disjoint_polygon_set` to not consider touching polygons as intersecting.

The scope of work here would be a couple hours to implement, test and PR in.

**Comment by davemfish** [comment]
👍  This almost sounds like a bugfix
