### ISSUE TITLE
Optimize `zonal_statistics` for multiple raster layers

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#310]
I needed to run `zonal_statistics` on each of several rasters, using the same aggregate vector. There's some duplicated work going on there - rasterizing the same vector once for each call. Maybe `zonal_statistics` could work on one or multiple base rasters?

The warp step also takes a lot longer than I'd like.

**Comment by phargogh** [comment]
👍 from me!  HRA has the same problem where we're aggregating over _lots_ of rasters using the same vector.  Some kind of optimization could stand to speed things up tremendously.

**Comment by dcdenu4** [comment]
I had this issue for Global Data Viewer analysis as well.

**Comment by davemfish** [comment]
During our meeting today, we agreed that it makes sense to require a pre-aligned stack of rasters when calling `zonal_statistics`.
