### ISSUE TITLE
Broken tests: `TypeError: issubclass() arg 1 must be a class`

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#328]
Apparently caused by the Cython 3.0.0 release, though somehow it's not fixed by pinning cython<3.0.0. This test is failing:
https://github.com/natcap/pygeoprocessing/blob/1e92d5aaf16c478565599a682ea8b9e60445593f/tests/test_geoprocessing.py#L130-L144

because `isinstance(func, (types.FunctionType, types.BuiltinFunctionType))` is `False`, it goes on to the next line, which triggers the error. 

It's failing on the function `calculate_slope`, which happens to be the first attribute of `pygeoprocessing` that it checks. The type of `calculate_slope` is `<class '_cython_3_0_0.cython_function_or_method'>`, which is _not_ a subclass of `types.FunctionType`.

**Comment by emlys** [comment]
Had to pin cython<3.0.0 in both requirements.txt and pyproject.toml. Included in #327.

**Comment by davemfish** [comment]
I ran into this and dug into it a bit before I saw this issue. So I have a proposed solution in #334
