### ISSUE TITLE
GDAL 3.7 changes behavior for signed bytes

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#329]
[Per the GDAL docs](https://gdal.org/user/raster_data_model.html#image-structure-domain):

> PIXELTYPE: This may appear on a GDT_Byte band (or the corresponding dataset) and have the value SIGNEDBYTE to indicate the unsigned byte values between 128 and 255 should be interpreted as being values between -128 and -1 for applications that recognise the SIGNEDBYTE type. Starting with GDAL 3.7, this metadata item is no longer used, as the Int8 data type is used for signed bytes.

It is not immediately clear to me if that means that the SIGNEDBYTE flag will be ignored entirely or if we should expect pygeoprocessing to handle both cases.  We should investigate this behavior and make a decision on how to handle this.  Until we do, signed integer raster operations in GDAL 3.7+ may have unexpected behavior.

**Comment by dcdenu4** [comment]
Can confirm that GDAL 3.7+ has changed behavior and causes tests to fail. GDT_Int8, added in 3.7, has a constant representation of 14. This is attempting to be mapped to `_GDAL_TYPE_TO_NUMPY_LOOKUP`, which does not include it.

**Comment by dcdenu4** [comment]
Also seeing an assertion error which looks like a `nodata` change
```python
FAILED tests/test_geoprocessing.py::TestGeoprocessing::test_new_raster_from_base_nodata_not_set - KeyError: 14
FAILED tests/test_geoprocessing.py::TestGeoprocessing::test_new_raster_from_base_unsigned_byte - AssertionError: 255 != -1
```
