### ISSUE TITLE
`calculate_slope` bug when nodata is `nan`

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#354]
`calculate_slope` compares DEM pixel values against the nodata value using `==`, which doesn't work if nodata is `nan`. You end up with `nan` values propagating to the slope output and not being reclassified to the expected nodata value. This caused an issue for a user in NDR - https://community.naturalcapitalproject.org/t/debugging-all-nan-in-n-export-output/4118/7

**Comment by phargogh** [comment]
Weird, I think this issue somehow wasn't closed with #356 .  Closing.
