### ISSUE TITLE
Support for python 3.12 in PyGeoprocessing?

### ISSUE THREAD

**Issue by shaoweiYoung** [natcap/pygeoprocessing#378]
Is there a python3.12 version of PyGeoprocessing available?

**Comment by phargogh** [comment]
Hello @shaoweiYoung !  The latest version of pygeoprocessing on the `main` branch does explicitly support python 3.12, we just haven't officially released it yet.

So if you have a compiler installed, you can install the latest version with:

```
pip install "git+https://github.com/natcap/pygeoprocessing.git@main#egg=pygeoprocessing"
```

We should do a release, though, so let me just check with my colleagues and we can see about a bugfix release soon.

**Comment by phargogh** [comment]
OK!  @shaoweiYoung Pygeoprocessing version 2.4.3 is now installable from the Python Package Index (https://pypi.org/project/pygeoprocessing/2.4.3/).  `conda-forge` builds will be created probably within the next day or so, once the automation catches up to the fact that there's a new release.

I will close this issue as resolved, but please feel free to reopen if needed.
