### ISSUE TITLE
ValueError in raster_calculator is incorrectly formatted

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#39]
The `ValueError` at https://github.com/natcap/pygeoprocessing/blob/master/src/pygeoprocessing/geoprocessing.py#L402 is using `logging` formatting rather than `%` string substitution, leading to a somewhat error message when triggered:

```python
Traceback (most recent call last):
  File "site-packages\taskgraph\Task.py", line 607, in add_task
  File "site-packages\taskgraph\Task.py", line 1071, in _call
  File "site-packages\natcap\invest\ndr\ndr.py", line 1145, in s_bar_calculate
  File "site-packages\pygeoprocessing\geoprocessing.py", line 405, in raster_calculator
ValueError: ('got a %s when trying to read %s at %s', None, ['F:/NDR\\intermediate_outputs\\s_accumulation.tif'], {'xoff': 7424, 'yoff': 2048, 'win_xsize': 256, 'win_ysize': 256})
```

This came up most recently on the forums at https://community.naturalcapitalproject.org/t/ndr-3-8-0-valueerror-encountered/857

**Comment by dcdenu4** [comment]
Good call James, for some reason I thought this was captured in a prior issue

**Comment by richpsharp** [comment]
Who is taking this issue? @dcdenu4 ?

**Comment by richpsharp** [comment]
@phargogh  I'm assigning you but feel free to reassign if you want.
