### ISSUE TITLE
Improve consistency of terminology around WKT projections

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#41]
Pygeoprocessing's API is quite consistent about how we name parameters and variables.  One notable exception about this, however, is that `get_raster_info()`'s returned dictionary includes the projection WKT string in a way that is inconsistent with the rest of the pygeoprocessing API.

* `pygeoprocessing.reproject_vector` accepts a parameter `target_wkt`
* `pygeoprocessing.warp_raster` accepts parameters `base_sr_wkt` and `target_sr_wkt`
* `pygeoprocessing.transform_bounding_box` accepts parameters `base_ref_wkt` and `target_ref_wkt`
* `pygeoprocessing.align_and_resize_rasster_stack` accepts `base_sr_wkt_list` and `target_sr_wkt`

At a minimum, `get_raster_info` should use `projection_wkt` as its key.

But perhaps we should also consider making the other WKT-related parameters more consistent.

CCing @richpsharp because we had talked about this in the office

**Comment by richpsharp** [comment]
Oh good point about making all these consistent. I'd propose `[raster_id]_projection_wkt` for everything where `raster_id` might be `base`, `target`, or dropped in the case of the keys in `get_raster_info` and `get_vector_info` -- just `projection_wkt` in those cases. Note the "projection" is consistent with `gdal`'s use of `.GetProjection()` for rasters and vectors.

**Comment by phargogh** [comment]
👍 the proposed naming scheme sounds good to me!

**Comment by richpsharp** [comment]
Ooop, I see you were "assigned" @dcdenu4. I'll put you as a reviewer on the PR.
