### ISSUE TITLE
Automatically create a PR into open release branches when commits are pushed to master

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#52]
Much like in https://github.com/natcap/invest/issues/66, we should be regularly PRing `master` into any open release branches.

**Comment by richpsharp** [comment]
Hey @phargogh, you did this right? If so could you label it "fixed" and close the issue? And if you haven't, how are there automatic PRs happening when we merge? :O

**Comment by phargogh** [comment]
Magic!  🧙
