### ISSUE TITLE
Convolve_2d returns different results if nodata is None

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#67]
When testing a raster where nodata was not set, therefore equal to `None`, I noticed `convolve_2d` returned different results then the SAME raster with nodata set to `-1`, where both rasters didn't actually have any nodata values.

Both function calls used: `ignore_nodata=True` and `mask_nodata=False`

I sent a gist and test data to @richpsharp for confirmation of this bug.

**Comment by richpsharp** [comment]
Fixed in #68
